GET http://localhost:3000/auth?password=437dd558-ab15-4bd9-9f83-c69f8a77e021
Accept: application/json

###

GET http://localhost:3000/auth/config?password=437dd558-ab15-4bd9-9f83-c69f8a77e021
Accept: application/json

###

GET http://localhost:3000/auth/env?password=437dd558-ab15-4bd9-9f83-c69f8a77e021
Accept: application/json

###

GET http://localhost:3000/auth/env?password=JSON.stringify(process.env)
Accept: application/json

###
